delete from tb_banktrade;
delete from tb_onlinetrade;
delete from tb_onlinetrade_confirm;
delete from tb_onlinetrade_expansion;
delete from tb_qrcode_order;
delete from tb_notify_notice;
delete from tb_withdraw;
delete from tb_merchant_entry;
delete from tb_order_entry;
delete from tb_merchant where username <> '9618';
