CREATE TABLE IF NOT EXISTS `tb_qrcode_order` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`code` VARCHAR(32) NOT NULL,
	`amount` DECIMAL(13, 3) NOT NULL,
	`discount_amount` DECIMAL(13, 3) NOT NULL,
	`total_amount` DECIMAL(13, 3) NOT NULL,
	`actual_amount` DECIMAL(13, 3) DEFAULT '0',
	`status` VARCHAR(32) NOT NULL DEFAULT 'ACQUIRED' COMMENT 'ACQUIRED | CANCELED | FINISHED',
	`create_timestamp` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	`update_timestamp` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `tb_qrcode_label` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(128) NOT NULL,
	`create_timestamp` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	`update_timestamp` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `tb_relationship_qrcode_label` (
	`code_id` INT NOT NULL,
	`code_label_id` INT NOT NULL,
	PRIMARY KEY (`code_id`, `code_label_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `tb_order_entry` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`order_number` VARCHAR(64) NOT NULL,
	`original_state` VARCHAR(32) NOT NULL COMMENT 'CREATED | CANCELED | CONFIRMED',
	`final_state` VARCHAR(32) NOT NULL COMMENT 'CANCELED | FINISHED AUTOMATICALLY | FINISHED MANUALLY | CONFIRMED',
	`notification_number` VARCHAR(64) DEFAULT NULL,
	`amount` DECIMAL(13, 3) DEFAULT NULL,
	`username` VARCHAR(128) DEFAULT NULL,
	`create_timestamp` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	`update_timestamp` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `tb_merchant_entry` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`merchant_username` VARCHAR(64) NOT NULL,
	`type` VARCHAR(64) NOT NULL COMMENT 'INCOME DIRECT | INCOME INDIRECT | EXPENDITURE',
	`order_number` VARCHAR(64) NOT NULL,
	`amount` DECIMAL(13, 3) NOT NULL,
	`balance` DECIMAL(13, 3) NOT NULL,
	`create_timestamp` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	`update_timestamp` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
